### PR TITLE
Upgrading AWS Java SDK to v2

### PR DESCRIPTION
**Pull request by mmccuiston**

### CODE REVIEW

**Comment by azagniotov** [comment]
Hi @mmccuiston, thanks for this! Could you please double check if any sections in the README need to be also updated?

**Comment by mmccuiston** [comment]
Hi @azagniotov - you bet!  Yes, the README needs some work.  I'll try and push an update shortly.

**Comment by mmccuiston** [comment]
I believe I have all the README.md updates submitted.

**Comment by azagniotov** [comment]
Thanks @mmccuiston Sorry, too busy with real life stuff. Will address this in a few days. I appreciate your patience.

**Review by azagniotov — APPROVED** [review]

**Comment by azagniotov** [comment]
@mmccuiston I just staged the new version for a sync with Maven Central, so please allow a few hours. Look for `io.github.azagniotov:dropwizard-metrics-cloudwatch:2.0.0`

Thanks again!

**Pull request merged**
