### PR TITLE
Update to cloudwatch 2.10.13

### PR DESCRIPTION
**Pull request by anilkumarmyla**
2.7.19 is kinda old (released in August), updating to latest as of today

### CODE REVIEW

**Comment by anilkumarmyla** [comment]
changelog at https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md

**Comment by azagniotov** [comment]
Hi @anilkumarmyla ,

Can you please check if as a result of this upgrade, if there are any change to the API and/or README has to be updated?

**Comment by anilkumarmyla** [comment]
No changes to cloudwatch APIs, so the upgrade should be seamless. Also mentioning individual third party dependencies with their exact versions in README is excessive, (this section)
```
Third-party dependencies
The library fetches the following transitive dependencies:
    io.dropwizard.metrics:metrics-core:4.0.2
    io.dropwizard.metrics:metrics-jvm:4.0.2
    software.amazon.awssdk:cloudwatch:2.7.19
```

Can we improve here a bit or do you want me to update 2.7.19 to 2.10.13?

**Comment by azagniotov** [comment]
Hi @anilkumarmyla, you are right - let's remove the aforementioned section, it just creates more maintenance chores.

**Comment by anilkumarmyla** [comment]
@azagniotov removed the section, thanks for reviewing

**Comment by azagniotov** [comment]
Will stage release of a new artifact in 30 mins!

**Comment by azagniotov** [comment]
@anilkumarmyla I have released `v2.0.1` to Maven Central, please allow a few hours for the artifact to sync with the live site.

**Pull request merged**
